name: Publish

on:
  push:
    branches:
      - main
      - release
  workflow_dispatch:

concurrency: release

permissions:
  contents: write
  issues: write

jobs:
  # ci:
  #   name: Continuous Integration
  #   uses: ./.github/workflows/ci.yaml

  release:
    name: Release
    # needs: ci
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install dependencies and build
        run: npm ci && npm run build

      - name: 'Semantic release'
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
